### ISSUE TITLE
POVME_pocket_id.py error (  index 0 is out of bounds for axis 0 with size 0)

### ISSUE THREAD

**Issue by MBenabderrahmane** [POVME/POVME#29]
Hi,
I'm trying the POVME_pocket_id.py on my pdbfile but I'm getting this error for the Step 9 : 
Traceback (most recent call last):
  File "POVME_pocket_id.py", line 1031, in <module>
    all_pockets = box_pts.separate_out_pockets()
  File "POVME_pocket_id.py", line 830, in separate_out_pockets
    pocket_indexes = numpy.hstack((pocket_indexes,numpy.array(numpy.nonzero(self.dist_matrix[pocket_indexes, :])[1])[0]))
IndexError: index 0 is out of bounds for axis 0 with size 0

Any help ?

**Comment by j-wags** [comment]
Hi @MBenabderrahmane ,

Thanks for getting in touch. Unfortunately we don't support the pocket ID functionality any more with POVME version 3. You might try a different tool, for example fpocket, for pocket detection.

David Koes has a nice list of available tools that might be more continuously supported moving forward: https://opensourcemolecularmodeling.github.io/#pocket-detection

Best,
Jeff

**Comment by BastienCasini** [comment]
Hi,

I am new to the field, and I am using your software for the calculation of pocket volume and area. But for some of my PDBs, I obtain the following error message : 

---------------------------------
STARTING CALC VOLUME
---------------------------------
Traceback (most recent call last):
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/bin/POVME3.py", line 2205, in <module>
    if __name__ == "__main__": dorun = runit(sys.argv)
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/bin/POVME3.py", line 1970, in __init__
    tmp = Multithreading([(index, pdb_object, parameters) for index, pdb_object in index_and_pdbs], parameters[NumProcessors], MultithreadingCalcVolumeTask)
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/bin/POVME3.py", line 146, in __init__
    for item in inputs: single_thread.value_func(item, None)
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/bin/POVME3.py", line 1087, in value_func
    my_peel = peel.peel(pdb, peel.defaultParams)
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/lib/python2.7/site-packages/POVME/packages/binana/peel.py", line 4082, in __init__
    self.characterize_features()
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/lib/python2.7/site-packages/POVME/packages/binana/peel.py", line 3577, in characterize_features
    self.characterize_aromatics()
  File "/mnt/c/CoursProjects/VirtualEnvironment/venv2.7/lib/python2.7/site-packages/POVME/packages/binana/peel.py", line 3678, in characterize_aromatics
    coords_CG = self.receptor.information.get_coordinates()[this_phe_CG][0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Which is really similar to what @MBenabderrahmane got. I can't find why that is the case, I changed the size of the inclusion sphere and also double-checked on pymol if the sphere was well placed and everything seems alright. Also, I am doing the same on about 10 PDB files, about half have this error and half are working. Would you have any clue about this?
